### ISSUE TITLE
Task compileDevelopmentExecutableKotlinJs fails with Kotlin 1.9.21

### ISSUE THREAD

**Issue by ju-h4** [littlektframework/littlekt-samples#3]
Task compileDevelopmentExecutableKotlinJs fails since commit **b495fc3**:

<details>
  <summary>
  Expand error log
  </summary>

  ```
> Task :compileDevelopmentExecutableKotlinJs FAILED
e: org.jetbrains.kotlin.backend.common.CompilationException: Back-end: Please report this problem https://kotl.in/issue
[***]/src/commonMain/kotlin/com/lehaine/littlekt/samples/game/SampleGame.kt:28:1
Problem with `class SampleGame : Game<GameScene> {
  constructor(context: Context) /* primary */ {
    super/*Game*/<GameScene>(context = context)
    /* <init>() */

  }


[...]


}

`
Details: Internal error in body lowering: java.lang.StackOverflowError: null
	at org.jetbrains.kotlin.ir.types.impl.IrSimpleTypeImpl.<init>(IrSimpleTypeImpl.kt:78)
	at org.jetbrains.kotlin.ir.types.impl.IrSimpleTypeImpl.<init>(IrSimpleTypeImpl.kt:72)
	at org.jetbrains.kotlin.ir.types.IrTypesKt.getDefaultType(irTypes.kt:179)
	at org.jetbrains.kotlin.backend.common.lower.inline.FunctionInlining$Inliner.getOriginalType$substituteSuperTypes(FunctionInlining.kt:754)

[...]

	at org.jetbrains.kotlin.backend.common.lower.inline.FunctionInlining$Inliner.getOriginalType$substituteSuperTypes(FunctionInlining.kt:754)
Caused by: java.lang.StackOverflowError
	... 1024 more


org.jetbrains.kotlin.backend.common.CompilationException: Back-end: Please report this problem https://kotl.in/issue
C:/git/littleKtSamples/src/commonMain/kotlin/com/lehaine/littlekt/samples/game/SampleGame.kt:28:1
Problem with `class SampleGame : Game<GameScene> {
  constructor(context: Context) /* primary */ {
    super/*Game*/<GameScene>(context = context)
    /* <init>() */

  }
  
[...]

}

`
Details: Internal error in body lowering: java.lang.StackOverflowError: null
	at org.jetbrains.kotlin.ir.types.impl.IrSimpleTypeImpl.<init>(IrSimpleTypeImpl.kt:78)
	at org.jetbrains.kotlin.ir.types.impl.IrSimpleTypeImpl.<init>(IrSimpleTypeImpl.kt:72)
	at org.jetbrains.kotlin.ir.types.IrTypesKt.getDefaultType(irTypes.kt:179)
	at org.jetbrains.kotlin.backend.common.lower.inline.FunctionInlining$Inliner.getOriginalType$substituteSuperTypes(FunctionInlining.kt:754)
[...]
	at org.jetbrains.kotlin.backend.common.lower.inline.FunctionInlining$Inliner.getOriginalType$substituteSuperTypes(FunctionInlining.kt:754)
Caused by: java.lang.StackOverflowError
	... 1024 more



Execution failed for task ':compileDevelopmentExecutableKotlinJs'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Internal compiler error. See log for more details
```
</details>

**Comment by LeHaine** [comment]
Interesting. That is a new one. This might take some digging as it seems like something failing with the JS compiler. Or perhaps a compiler bug? Either way I will check it out.

**Comment by ju-h4** [comment]
> Interesting. That is a new one. This might take some digging as it seems like something failing with the JS compiler. Or perhaps a compiler bug? Either way I will check it out.

Yes, I think so, too, thanks.
Until then I'm using littlekt 0.8.0 and Kotlin 1.9.10, which seems to work.

**Comment by LeHaine** [comment]
I did some digging and found that this is happening on inline reified `Game.addScene<T>(scene: T)` function. The function itself calls the `Game.addScene(type: KClass<Type>, scene: Type)`. For some reason, the inline function thinks its calling itself and gets into an infinite loop. I updated the samples to call the `KClass` function and it compiles fine.
